title: isikoro.dev
description: いしこログ
theme: jekyll-theme-minimal
url: "https://blog.isikoro.dev"
baseurl: ""
timezone: Asia/Tokyo
x_username: "mot1173137"
# default_og_image: "/assets/images/og/default.png"
# future: true

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true


# ↓別のテーマ
# jekyll-theme-slate 
